layout_spectrum: 0.12315639572356375
typography_spectrum: 0.7737379172944123
color:
  brandColors:
    - '#000000'
    - '#333333'
    - '#FF358B'
    - '#01B0F0'
    - '#AEEE00'
  brandStrength: 0.8433192402812293
  lightness: 0.5043419730425397
  saturation: 0.988799368882146
  rhythmicContrast: 0.11257772572181823
content_rating:
  adult: false
github: true
opengraph:
  type: ''
  appId: ''
analytics: {}
author:
  name: ''
  url: ''
  email: ''
logo: null
name: KGW
cta: {}
navigation:
  - name: KGW Manifesto
    id: 8f551792-6503-4c76-9d7f-4383b7607544
    type: content
  - name: Parpolity
    id: 66747b1e-c9dc-4894-b295-f2ed18413188
    type: content
favicon: null
title: Keep Grid Weird
content: []
description: "utopia \uD83D\uDC41 love \uD83D\uDC41 dreams \uD83D\uDC41 resistance"
purpose: []
