layout_spectrum: 0.19230286948585718
typography_spectrum: 0.6450147543246351
color:
  brandColors:
    - '#000000'
    - '#333333'
    - '#FF358B'
    - '#01B0F0'
    - '#AEEE00'
  brandStrength: 0.09741224627628332
  lightness: 0.7623992626678826
  saturation: 0.32850529203163736
  rhythmicContrast: 0.27315999124650986
content_rating:
  adult: false
github: true
opengraph:
  type: ''
  appId: ''
analytics: {}
author:
  name: ''
  url: ''
  email: ''
logo: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/8bb54a69-cb52-4479-9417-a68dd9d6d2ab.jpg
name: KGW
cta: {}
navigation:
  - name: KGW Manifesto
    id: 8f551792-6503-4c76-9d7f-4383b7607544
    type: content
  - name: Parpolity
    id: 66747b1e-c9dc-4894-b295-f2ed18413188
    type: content
favicon: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/ed8bfb04-6b38-4db5-bfb7-b6bada247547.jpg
title: Keep Grid Weird
content: []
description: "\uD83D\uDC41\uD83D\uDC41\uD83D\uDC41"
purpose: []
