typography_spectrum: 0.6595520182904594
content_rating:
  adult: false
color:
  brandColors:
    - '#000000'
    - '#333333'
    - '#FF358B'
    - '#01B0F0'
    - '#AEEE00'
  brandStrength: 0.6622962077216494
  lightness: 0.3792440008204246
  saturation: 0.6418584533516171
  rhythmicContrast: 0.36592465013367037
github: true
opengraph:
  type: ''
  appId: ''
layout_spectrum: 0.7989501952153105
analytics: {}
author:
  name: ''
  url: ''
  email: ''
logo: null
name: KGW
cta: {}
navigation:
  - name: KGW Manifesto
    id: 8f551792-6503-4c76-9d7f-4383b7607544
    type: content
  - name: Parpolity
    id: 66747b1e-c9dc-4894-b295-f2ed18413188
    type: content
favicon: null
title: Keep Grid Weird
content: []
description: "utopia \uD83D\uDC41\uD83D\uDC41\uD83D\uDC41 resistance "
purpose: []
