typography_spectrum: 0.8395928198006004
content_rating:
  adult: false
color:
  brandColors:
    - '#FFFFFF'
    - '#CCCCCC'
    - '#999999'
    - '#4D4D4D'
    - '#333333'
  brandStrength: 0.9276992278173566
  lightness: 0.45641640457324684
  saturation: 0.24891139077953994
  rhythmicContrast: 0.8172235200181603
github: true
opengraph:
  type: ''
  appId: ''
layout_spectrum: 0.8064247285947204
analytics: {}
author:
  name: ''
  url: ''
  email: ''
logo: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/8bb54a69-cb52-4479-9417-a68dd9d6d2ab.jpg
name: KGW
cta: {}
navigation:
  - name: KGW Manifesto
    id: 8f551792-6503-4c76-9d7f-4383b7607544
    type: content
  - name: Parpolity
    id: 66747b1e-c9dc-4894-b295-f2ed18413188
    type: content
favicon: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/ed8bfb04-6b38-4db5-bfb7-b6bada247547.jpg
title: Keep Grid Weird
content: []
description: "\uD83D\uDC41\uD83D\uDC41\uD83D\uDC41"
purpose: []
