layout_spectrum: 0.9002428073399138
typography_spectrum: 0.3524499914696495
color:
  brandColors:
    - '#000000'
    - '#333333'
    - '#FF358B'
    - '#01B0F0'
    - '#AEEE00'
  brandStrength: 0.8482759667478391
  lightness: 0.5021294206403897
  saturation: 0.9863602360942871
  rhythmicContrast: 0.11787995310758453
content_rating:
  adult: false
github: true
opengraph:
  type: ''
  appId: ''
analytics: {}
author:
  name: ''
  url: ''
  email: ''
logo: null
name: KGW
cta: {}
navigation:
  - name: KGW Manifesto
    id: 8f551792-6503-4c76-9d7f-4383b7607544
    type: content
  - name: Parpolity
    id: 66747b1e-c9dc-4894-b295-f2ed18413188
    type: content
favicon: null
title: Keep Grid Weird
content: []
description: "utopia \uD83D\uDC41 love \uD83D\uDC41 dreams \uD83D\uDC41 resistance"
purpose: []
